### ISSUE TITLE
Add publicTransportTimeTable

### ISSUE THREAD

**Issue by eifinger** [eifinger/here_travel_time#3]
https://developer.here.com/documentation/routing/topics/resource-param-type-routing-mode.html#type-route-feature

**Comment by scstraus** [comment]
Hi, I tried this mode out using the API and it gives me correct results whereas the PublicTransport option does not.. I'm guessing that PublicTransport only works with routes publishing real time data, whereas PublicTransportTimetable looks at all routes for which it has a timetable (though may not use realtime information).  This feature would be a great one for me.
